import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Login } from './login/login'
import '../node_modules/bootstrap/dist/css/bootstrap.css'
import '../node_modules/bootstrap-icons/font/bootstrap-icons.css'
import '../node_modules/bootstrap/dist/js/bootstrap.bundle'
//import { DataBinding } from './components/data-binding/data-binding'
//import { Flipkart } from './components/flipkart/flipkart'
import { Nasa } from './components/nasa/nasa'
import { EventBinding } from './components/Event binding/event-binding'
import { MouseDemo } from './components/mouse demo/mouse-demo'
import { PasswordStrength } from './components/password-strength/password-strength'
import { DebounceDemo } from './components/debounce demo/debounce-demo'
import { TimerDemo } from './components/timer demo/timer-demo'
import { TimeoutDemo } from './components/timeout demo/timeout-demo'
import { LoadingStatus } from './components/loading status/loading-status'
import { FormDemo } from './components/form demo/form-demo'
import { FormikComponentDemo } from './components/yup-form/yupform'
import { HookFormDemo } from './components/hook form demo/hook-form-demo'
import { ControlleDemo } from './components/controlled demo/controle'
import { ConditionDemo } from './components/condition demo/condition-demo'
import { ContextDemo, Level1 } from './components/context demo/context-demo'
import { FakeStore } from './components/fakestore/fakestore'
import { TransportDemo } from './components/transport demo/transport-demo'
import { LifeCycleDemo, Register } from './components/lifecycle-component/login'
import { TutorialIndex } from './video tutorial/tutorial-index'
import { FakestoreIndex } from './shopping/fakestore-index'
import { CookiesProvider } from 'react-cookie'
import { VideoLibrary } from './video-library/video-library-index'
import { ReducerDemo } from './components/reducer-demo/reducer-demo'
import { SuspenseDemo } from './components/suspense-demo/suspense-demo'
import { ClassDemo } from './class-component/class-demo'
import { DemoClass } from './class-component/demo-class'
import { Toolbar } from './class-component/toolbar'
import App from './chai/bgchanger'
import Chai from '../pass generator/pass'
import { Binding } from '../practiceexm/state'
//import { Mom } from '../practiceexm/mom'
import { Bomb } from '../practiceexm/check'
import { Bank } from '../practiceexm/bank'
import { Bounce } from '../practiceexm/baunce'
import { Time } from '../practiceexm/time'
import { OutTime } from '../practiceexm/outtime'
import { Form } from '../practiceexm/form'
import { Demo } from '../practiceexm/demo'
import { Dot } from '../practiceexm/form2'
import { Component } from '../practiceexm/yup'
import { Hook } from '../practiceexm/form3'
import { DataGrid } from './controlled-componants/data-grid'
import { Navbar } from './controlled-componants/navbar'
import { Conditi } from '../practiceexm/condition'
import { Child } from '../practiceexm/transf'
import { Sign } from '../practiceexm/componant'
import { Reduce } from '../practiceexm/reduce'
import { ClassBemo } from '../practiceexm/class'


createRoot(document.getElementById('root')).render(
    <CookiesProvider>
    <ClassBemo />
    </CookiesProvider>
)
